alist/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from user import views as UserViews

urlpatterns = [
    path('', include('home.urls')),
    path('product/', include('product.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('admin/', admin.site.urls),

    path('accountform/',  UserViews.accountform, name='accountform'),
    path('login/',  UserViews.loginform, name='loginform'),
    path('logout/',  UserViews.logoutfunc, name='logoutfunc'),
    path('register/',  UserViews.registerform, name='registerform'),
    path('update/', UserViews.userupdate, name='userupdate'),
    path('password/', UserViews.userpassword, name='userpassword'),
]
if settings.DEBUG:    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.index, name = 'index'),
    path('about/', views.about, name ='about'),
    path('contact/', views.contact, name = 'contact'),
    path('category', views.category, name='category'),
    path('product/<str:id>/<slug:slug>', views.product_list, name='product_list'),
    path('product-detail/<str:id>/<slug:slug>', views.prod_detail, name='prod_detail'),  
]

order/urls.py
from django.urls import path
from . import views


app_name = 'order'



urlpatterns = [
    path('order/', views.index, name ='order'),
    path('addtoshopcart/', views.addtoshopcart, name = 'addtoshopcart'),
    path('shopcart/', views.shopcart, name = 'shopcart'),
    path('updatequantity/', views.updatequantity, name = 'updatequantity'),
    path('deletefromcart/<str:id>', views.deletefromcart, name = 'deletefromcart'),
    path('checkout/', views.checkout, name = 'checkout'),
    path('placeorder/', views.placeorder, name = 'placeorder'),
    path('ordercompleted/', views.ordercompleted, name = 'ordercompleted'),
]

product/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.index, name ='product')
]

home/models.py
from django.db import models

from django.forms import Textarea, TextInput
from django.forms import ModelForm
from ckeditor_uploader.fields import RichTextUploadingField



# Create your models here.
class Setting(models.Model):
    STATUS =(
        ('True', 'True'),
        ('False', 'False'),
    )

    title = models.CharField(max_length=100)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255, null=True)
    company = models.CharField(max_length=50, null=True)
    address = models.CharField(max_length=100)
    phone = models.CharField( null=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    icon = models.ImageField(blank=True,null=True,  upload_to='images/')
    logo = models.ImageField(blank=True,null=True, upload_to='images/')
    cart_icon = models.ImageField(blank=True,null=True, upload_to='images/')
    menu_icon = models.ImageField(blank=True,null=True, upload_to='images/')
    facebook = models.CharField(blank=True, max_length=50)
    instagram = models.CharField(blank=True, max_length=50)
    twitter = models.CharField(blank=True, max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    about =RichTextUploadingField(blank=True)
    about2 =RichTextUploadingField(blank=True, default='aboutto')
    contact =RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    
    def __str__(self):
        return self.title


class Brand(models.Model):
    title = models.CharField(max_length=10,blank=True,null=True)
    brands = models.ImageField(blank=True,null=True, upload_to='images/')    

    def __str__(self):
        return self.title


class Testimonial(models.Model):
    name = models.CharField(max_length=20,blank=True,null=True)
    comment = models.CharField(max_length=250,blank=True,null=True, default='Thumbs Up Alist')
    testimos = models.ImageField(blank=True,null=True, upload_to='images/')

    def __str__(self):
        return self.name

 
class ContactMessage(models.Model):
    STATUS =(
        ('New', 'New'),
        ('Read', 'Read'),
        ('Pending', 'Pending'),
        ('Closed', 'Closed'),
    )

    name = models.CharField(blank=True, max_length=20)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True, max_length=50)
    message = models.TextField(blank=True, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    note = models.CharField(blank=True, max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class ContactForm(ModelForm):
    class Meta:
        model= ContactMessage
        fields = ['name', 'email', 'subject', 'message']
       

product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm


from django.urls import reverse
from django.utils.safestring import mark_safe
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.
class Category(models.Model):
    STATUS =(
        ('True', 'True'),
        ('False', 'False'),
    )
    title = models.CharField(max_length=150)
    image = models.ImageField(blank=True, upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(null=False, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Product(models.Model):
    STATUS =(
        ('True', 'True'),
        ('False', 'False'),
    )

    AVAILABLE =(
        ('In Stock', 'In Stock'),
        ('Out Of Stock', 'Out Of Stock'),
        ('ReStocked', 'ReStocked'),
    )
    
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=150, blank=True)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image= models.ImageField(blank=True, upload_to='images/')
    price = models.FloatField(null=True, blank=True)
    sizes = models.CharField(max_length=30, null=True, default='Large')
    discount_price= models.FloatField(blank=True, null=True)
    available= models.CharField(choices=AVAILABLE, max_length=15, default='In Stock')
    quantity_instock = models.IntegerField(null=True, blank=True, default=1000)
    minquantity = models.IntegerField(blank=True)
    amount = models.IntegerField(null=True, blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(null=False, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    featured = models.BooleanField(blank=True)
    latest = models.BooleanField(blank=True)
    banner = models.BooleanField(blank=True)
    offer = models.BooleanField(blank=True)
    detail = RichTextUploadingField()
    
    def __str__(self):
        return self.title
    
    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug}) 


class Images(models.Model):
    product=models.ForeignKey(Product,on_delete=models.DO_NOTHING, blank=True)
    image= models.ImageField(blank=True, upload_to='images/')

home/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse 
from django.contrib import messages
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from .models import *
from product.models import *
from user.models import UserProfile


# Create your views here.
def index(request):
    setting= Setting.objects.get(pk=1)
    brands = Brand.objects.all()
    testimo = Testimonial.objects.all()
    banner = Product.objects.get(banner=True)
    offer = Product.objects.get(offer=True)
    category = Category.objects.all()[:3]
    featured = Product.objects.filter(featured= True)
    latest = Product.objects.filter(latest= True)[:4]
    latest2 = Product.objects.filter(latest= True).order_by('-id')[:4]
    
    
    context={
        'setting':setting,
        'brands': brands,
        'testimo':testimo,
        'banner': banner,
        'offer': offer,
        'category': category,
        'featured': featured,
        'latest': latest,
        'latest2': latest2,
    }
    return render(request, 'index.html', context)
    

def about(request):
    setting = Setting.objects.get(pk=1)
    brands = Brand.objects.all()
    category = Category.objects.all()

    context = { 'setting': setting,
                'brands': brands,
                'category': category,
    }            

    return render(request, 'about.html', context)


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"Your message has been sent! Our Customer Service Team will reach you soon.")
            return redirect('/contact')


    setting = Setting.objects.get(pk=1)
    form = ContactForm
    brands = Brand.objects.all()
    category = Category.objects.all()
       
    context= { 'setting': setting,
                'form': form,
                'brands': brands,
                'category': category,                
    }

    return render(request, 'contact.html', context)

def category(request):
    setting= Setting.objects.get(pk=1)
    brands = Brand.objects.all()
    offer = Product.objects.get(offer=True)
    category = Category.objects.order_by('-created_at').filter(status=True)
    paginator = Paginator(category,4)
    page= request.GET.get('page')
    paged_category = paginator.get_page(page)
    
    context= {
            'setting': setting,
            'brands': brands,
            'offer': offer,
            'category': paged_category,
    }

    return render(request, 'categories.html', context)

def product_list(request,id,slug):
    setting= Setting.objects.get(pk=1)
    category = Category.objects.all()
    catdata= Category.objects.get(pk=id)
    products = Product.objects.filter(category__id=id)
    # products2 = Product.objects.filter(category_id=id).order_by('-id')[:4]
    paginator = Paginator(products,2)
    page= request.GET.get('page')
    paged_products = paginator.get_page(page)
    

    context= {
                'setting': setting,
                'category': category,
                'catdata': catdata,
                'products': paged_products,
                # 'products2': products2,
    }

    return render(request, 'products.html', context)
    # return HttpResponse(products)



def prod_detail(request,id,slug):
    setting= Setting.objects.get(pk=1)
    category = Category.objects.all()
    products = Product.objects.filter(category_id=id)
    product = Product.objects.get(pk=id)
    images = Images.objects.filter(product_id=id)

    
    context= {
                'setting': setting,
                'category': category,
                'products': products,
                'product': product,
                'images': images,
    }

    return render(request, 'product-details.html', context)























# from django.shortcuts import render, redirect
# from django.http import HttpResponse
# from django.contrib import messages
# from . models import *
# from product . models import *
# from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

# # Create your views here.


# def index(request):
#     setting = Setting.objects.get(pk=1)
#     brands = Brand.objects.all()
#     testimo = Testimonial.objects.all()
#     category = Category.objects.all()[:3]
#     banner = Product.objects.get(banner=True)
#     offer = Product.objects.get(offer=True)
#     featured = Product.objects.filter(featured= True)
#     latest = Product.objects.filter(latest= True)[:4]
#     latest2 = Product.objects.filter(latest= True).order_by('-id')[:4]
    

#     context = {
#         'setting':setting,
#         'brands':brands,
#         'testimo':testimo,
#         'banner': banner,
#         'offer': offer,
#         'category': category,
#         'featured': featured,
#         'latest': latest,
#         'latest2': latest2,
#     }
#     # return HttpResponse('I am determine to be a certified programmer')
#     return render(request, 'index.html', context)

# def about(request):
#     setting = Setting.objects.get(pk=1)
#     brands = Brand.objects.all()
#     category = Category.objects.all()

#     context = {
#         'setting':setting,
#         'brands': brands,
#         'category': category,
#     }

    
#     return render(request, 'about.html', context)
#     return HttpResponse('About page created')




# def contact(request):
#     if request.method == 'POST':
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             form.save()
#             messages.success(request, "Your message has benn sent! Our customer service team will reach you soon.")
#             return redirect('/contact')


#     setting = Setting.objects.get(pk=1)
#     form = ContactForm
#     brands = Brand.objects.all()

#     context= { 'setting': setting,
#                'form': form,
#                'brands': brands,

#     }

#     return render(request, 'contact.html', context)



# def category(request):
#     setting= Setting.objects.get(pk=1)
#     brands = Brand.objects.all()
#     offer = Product.objects.get(offer=True)
#     category = Category.objects.order_by('-created_at').filter(status=True)
#     paginator = Paginator(category,4)
#     page= request.GET.get('page')
#     paged_category = paginator.get_page(page)
    
#     context= {
#             'setting': setting,
#             'brands': brands,
#             'offer': offer,
#             'category': paged_category,
#     }

#     return render(request, 'categories.html', context)

# def product_list(request,id,slug):
#     setting= Setting.objects.get(pk=1)
#     category = Category.objects.all()
#     catdata= Category.objects.get(pk=id)
#     products = Product.objects.filter(category__id=id)
#     paginator = Paginator(products,2)
#     page= request.GET.get('page')
#     paged_products = paginator.get_page(page)
    

#     context= {
#                 'setting': setting,
#                 'category': category,
#                 'catdata': catdata,
#                 'products': paged_products,
#     }

#     return render(request, 'products.html', context)
#     # return HttpResponse(products)



# def prod_detail(request,id,slug):
#     setting= Setting.objects.get(pk=1)
#     category = Category.objects.all()
#     products = Product.objects.filter(category_id=id)
#     product = Product.objects.get(pk=id)
#     images = Images.objects.filter(product_id=id)

    
#     context= {
#                 'setting': setting,
#                 'category': category,
#                 'products': products,
#                 'product': product,
#                 'images': images,
#     }

#     return render(request, 'product-details.html', context)

product/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    return HttpResponse('New App')

home/templates/about.html
{% extends 'base.html' %}
{% load static %}


{% block title %} About Us|{{ setting.title}} {% endblock title %}

{% block keywords %} {{setting.keywords}} {% endblock keywords %}

{% block description %} {{setting.description}} {% endblock description %}
    

        

<!-- Header and banner  -->
{% block header %} {% include "acheader.html" %} {% endblock header %}
<!-- Header and banner done  -->

<!-- Content  -->
{% block content %}  

   <!-- Account Page  -->
    <div class="account-page">
        <div class="container">
            <h2 class="title">About Us</h2>
            <div class="row">
                <div class="col-2">
                    {{setting.about|safe}}
                </div>
                <div class="col-2">
                    {{setting.about2|safe}}
                </div>
            </div>
        </div>
    </div>
   <!-- Account Page Done  -->

   {% endblock content %}                       
   <!-- Content done  -->

   <!-- footer   -->
   {% block footer %}  {% include "footer.html" %} {% endblock footer %}
   <!-- footer done  -->

   

home/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="{% block keywords %} Home {% endblock keywords %}"> 
    <meta name="description" content="{% block description %} Home {% endblock description %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %} Home|Prodigious Storeapp {% endblock title %}</title>

    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"> 
    <link rel="stylesheet" href="{% static '' %}css/main.css"> 
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    
    <link rel="icon" type="image/png" sizes="96x96" href="{{setting.icon.url}}">
</head>

<body>

    <!-- Header and banner  -->
    {% block header %} {% endblock header %}
    <!-- Header and banner done  -->

    <!-- Content  -->
    {% block content %} {% endblock content %}
    <!-- Content done  -->

    <!-- offer products  -->
    {% block offer %} {% endblock offer %}
    <!-- offer products done -->

    <!-- Testimonials  -->
    {% block testimonials %} {% endblock testimonials %}
    <!-- Testimonials done -->

    <!-- brands   -->
    {% block brands %} {% endblock brands %}
    <!-- brands done  -->

    <!-- footer   -->
    {% block footer %} {% endblock footer %}
    <!-- footer done  -->

     <!-- js for togglemenu  -->
    
    <script type="text/javascript" src="{% static 'js/togglemenu.js' %}"></script> 
    
    <!-- js for togglemenu done -->

    <!-- js for gallerry  -->
    <script type="text/javascript" src="{% static 'js/gallery.js' %}"></script> 
    <!-- js for gallerry done -->

    <!-- js for toggleform  -->
    <script type="text/javascript" src="{% static 'js/toggleform.js' %}"></script> 
    <!-- js for toggleform done -->
     
   
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>

</body>
</html>

home/templates/brands.html
<!-- brands  -->
<div class="brands">
    <div class="small-container">
        <div class="row">
            {% for brand in brands %}
                <div class="col-5">
                    <img src="{{brand.brands.url}}" >
                </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- brands done  -->

home/templates/footer.html
 <!-- footer  -->
 <div class="footer">
    <div class="container">
        <div class="row">
            <div class="footer-col-1">
                <h3>Visit Our Store</h3>
                <p>Be assured of exciting shopping Experience </p>
            </div>
            <div class="footer-col-2">
                <a href="{% url 'index' %}"><img src="{{setting.logo.url}}"></a>
                <p>We have top quality products at best prices</p>
            </div>
            <div class="footer-col-3">
                <ul>
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'about' %}">About</a></li>
                    <li><a href="{% url 'contact' %}">Contact Us</a></li>
                    <li><a href="">Your Cart</a></li>
                </ul>
            </div>
            <div class="footer-col-4">
                <ul>
                    <li><a href="">Facebook</a></li>
                    <li><a href="">Instagram</a></li>
                    <li><a href="">Twitter</a></li>
                    <li><a href="">Whatsapp</a></li>
                </ul>
            </div>
        </div>
        <hr>
        <p class="copyright">Copyright 2021 &copy; Enos A-list Stores</p>
    </div>
</div>
<!-- footer done  -->

home/templates/header.html
{% load static %}
<!-- Header and banner combined  -->
<div class="headermain">
    <div class="container">
        <div class="header">
            <div class="logo">
                <a href="{% url 'index' %}"><img src="{{setting.logo.url}}" alt="company logo here"></a>
            </div>
            <div class="navbar">
                <ul id="MenuItems">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="{% url 'category' %}">Products</a></li>
                    {% if user.id is not None %}                   
                        <li><a href="{% url 'user' %}"><img src="{{profile.image.url}}" alt="" style="border-radius: 30px; height:50px"></a></li>
                        <li>                           
                           <a href="{% url 'user' %}">Welcome!
                                {% if request.user.first_name %}
                                    {{request.user.first_name}}
                                {% else %}
                                    {{request.user.username}}
                                {% endif %}
                           </a>
                        </li>
                        <li><a href="{% url 'logoutfunc' %}">Logout</a></li>
                        <li><a href="">Change Password</a></li>
                    {% else %}
                        <li><a href="{% url 'accountform' %}">Account</a></li> 
                    {% endif %}	
                </ul>
            </div>
            <a href="{% url 'order:shopcart' %}"><img src="{{setting.cart_icon.url}}" alt="shop cart" width="30px" height="30px">
                {% if itemcount > 0 %}
                    <span class="badge red z-depth-1 mr-1">{{ itemcount }}</span>
                {% else %}
                    <span class="badge red z-depth-1 mr-1">0</span>
                {% endif %}              
            </a>
            <img src="{{setting.menu_icon.url}}" class="menu-icon" onclick="menutoggle()">
        </div> 
        {% if messages %}
            {% for message in messages  %}
                <div  class="alert alert-{{message.tags}}" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>													
                    {{ message }}
                </div>									  
            {% endfor %}								  
        {% endif %}	  
        <div class="row">
            <div class="col-2">
                <h1>Give Your Work Some <br> Class And Style!</h1>
                <p>“You can have anything you want if you want it badly enough. You can  <br>be anything
                     you want to be, do anything you set out to accomplish <br>
                      if you hold to that desire with singleness of purpose.”
                </p>
                    <a href="{% url 'category' %}" class="buttons">Explore Now &#8594;</a>
            </div>
            <div class="col-2">
                <img src="{{banner.image.url}}">
            </div>
        </div>
    </div>
</div>
<!-- Header and banner done  -->

home/templates/prod-header.html
<div class="headermain">
    <div class="container">
        <div class="header">
            <div class="logo">
                <a href="{% url 'index' %}"><img src="{{setting.logo.url}}" alt="company logo here"></a>
            </div>
            <div class="navbar">
                <ul id="MenuItems">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="{% url 'category' %}">Products</a></li>
                    {% if user.id is not None %}                   
                        <li><a href="{% url 'user' %}"><img src="{{profile.image.url}}" alt="" style="border-radius: 30px; height:40px"></a></li>
                        <li>                           
                           welcome!<a href="{% url 'user' %}">
                                {% if request.user.first_name %}
                                    <p><strong> {{request.user.first_name}}</strong></p>    
                                {% else %}
                                    <p><strong>{{request.user.username}}</strong></p>
                                {% endif %}
                           </a>
                        <li><a href="{% url 'logoutfunc' %}">Logout</a></li>
                        <li><a href="">Change Password</a></li>
                    {% else %}
                        <li><a href="{% url 'accountform' %}">Account</a></li> 
                    {% endif %}	
                </ul>
            </div>
            <a href="{% url 'order:shopcart' %}"><img src="{{setting.cart_icon.url}}" alt="shop cart" width="30px" height="30px">
                {% if itemcount > 0 %}
                    <span class="badge red z-depth-1 mr-1">{{ itemcount }}</span>
                {% else %}
                    <span class="badge red z-depth-1 mr-1">0</span>
                {% endif %}              
            </a>
            <img src="{{setting.menu_icon.url}}" class="menu-icon" onclick="menutoggle()">
        </div>
        {% if messages %}
            {% for message in messages  %}
                <div style="width: 400px;" class="alert alert-{{message.tags}}" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>													
                    {{ message }}
                </div>									  
            {% endfor %}								  
        {% endif %}	
    </div>
</div>

home/templates/product-details.html
{% extends 'base.html' %}


{% load humanize %}


{% block title %} {{product.title}} Products {% endblock title %}

{% block keywords %} {{product.keywords}} {% endblock keywords %}

{% block description %} {{product.description}} {% endblock description %}
    
<!-- Header   -->
{% block header %} {% include "prod-header.html" %} {% endblock header %}
<!-- Header done  -->


{% block content %}
    <!-- Single  product details  -->

    <div class="small-container single-product">
        <div class="row">
            <div class="col-2">
                <img src="{{product.image.url}}" width="100%" id="ProductImg">
                <div class="small-img-row"> 
                    {% if images %}
                        {% for item in images %}
                            <div class="small-img-col">
                                <img src="{{item.image.url}}" width="100%" class="SmallImg">
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="col-2">
                <p>{{product.title}}</p>
                <h1>{{product.description}}</h1>
                <h4><span style="color: #ff523b;">{{product.available}}</span></h4>
                <h4>
                    {% if product.discount_price %}
                        <del>${{product.price | floatformat:2 | intcomma}}</del>
                        <span>${{ product.discount_price| floatformat:2 | intcomma }}</span>
                    {% else %}
                        <span>${{ product.price| floatformat:2 | intcomma }}</span>
                    {% endif %} 
                </h4>
                <h4><strong>Available Sizes:</strong><span style="color: #ff523b;">{{product.sizes}}</span></h4>
                <form  action="{% url 'order:addtoshopcart' %}" method="POST">
                {% csrf_token %}
                    <select name="size">
                        <!-- <option>Select Size</option> -->
                        <option value="Small">Small</option>
                        <option value="Medium">Medium</option>
                        <option value="Large">Large</option>
                        <option value="XL">XL</option>
                        <option value="XXL">XXL</option>
                    </select>
                    <label>Qty:</label>
                    <input type="number" name="quantity" value="1" min="{{product.minquantity}}" max="{{product.quantity_instock}}">
                    <input type="submit" class="buttons" value="Add To Cart">
                    <!-- <a href="" class="btn">Add To Cart</a> -->
                    <input type="hidden" name="prodid" value="{{ product.id }}">
                </form>
                <h3>Product Details<i class="fa fa-indent"></i></h3>
                <br>
                <p>{{product.detail|safe}}</p>
            </div>
        </div>
    </div>
    <!-- title  -->
    <div class="small-container">
        <div class="row row-2">
            <h2>Related Products</h2>
            <a href="{% url 'category' %}"><p>View More</p></a>
        </div>
    </div>
    <!-- products  -->
    <div class="small-container">
        <div class="row">
            {% if products %}
                {% for item in products %}
                    <div class="col-4">
                        <a href="{% url 'prod_detail' item.id item.slug %}"><img src="{{ item.image.url}}"></a>
                        <a href="{% url 'prod_detail' item.id item.slug %}"><h4>{{item.title}}</h4></a>
                        <a href="{% url 'prod_detail' item.id item.slug %}" class="category">{{item.category}}</a>
                        <div class="rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-o"></i>
                        </div>
                        <p class="price">
                            {% if item.discount_price %}
                                <del>#{{item.price | floatformat:2 | intcomma}}</del>
                                <span>#{{ item.discount_price | floatformat:2 | intcomma }}</span>
                            {% else %}
                                <span>#{{ item.price | floatformat:2 | intcomma}}</span>
                            {% endif %} 
                        </p>
                    </div>
                {% endfor %}
            {% endif %}
            <div>
        </div>
    </div>
</div>
    <!-- product details end here  -->  
    {% endblock content %}

    <!-- footer   -->
    {% block footer %}  {% include "footer.html" %} {% endblock footer %}
    <!-- footer done  -->