alist/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from user import views as UserViews

urlpatterns = [
    path('', include('home.urls')),
    path('product/', include('product.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('admin/', admin.site.urls),

    path('accountform/',  UserViews.accountform, name='accountform'),
    path('login/',  UserViews.loginform, name='loginform'),
    path('logout/',  UserViews.logoutfunc, name='logoutfunc'),
    path('register/',  UserViews.registerform, name='registerform'),
    path('update/', UserViews.userupdate, name='userupdate'),
    path('password/', UserViews.userpassword, name='userpassword'),
]
if settings.DEBUG:    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.index, name = 'index'),
    path('about/', views.about, name ='about'),
    path('contact/', views.contact, name = 'contact'),
    path('category', views.category, name='category'),
    path('product/<str:id>/<slug:slug>', views.product_list, name='product_list'),
    path('product-detail/<str:id>/<slug:slug>', views.prod_detail, name='prod_detail'),  
]

order/urls.py
from django.urls import path
from . import views


app_name = 'order'



urlpatterns = [
    path('order/', views.index, name ='order'),
    path('addtoshopcart/', views.addtoshopcart, name = 'addtoshopcart'),
    path('shopcart/', views.shopcart, name = 'shopcart'),
    path('updatequantity/', views.updatequantity, name = 'updatequantity'),
    path('deletefromcart/<str:id>', views.deletefromcart, name = 'deletefromcart'),
    path('checkout/', views.checkout, name = 'checkout'),
    path('placeorder/', views.placeorder, name = 'placeorder'),
    path('ordercompleted/', views.ordercompleted, name = 'ordercompleted'),
]

order/models.py
from django.db import models
from django.contrib.auth.models import User
# from django.forms import  NumberInput, Select

from django.forms import ModelForm
from  product.models import Product
from django.forms import Select


class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField(blank=True ,null=False)
    # size = models.CharField(max_length=10, choices=SIZE, blank=True ,null=True)
    size = models.CharField(max_length=10,blank=True ,null=True)
    order_code = models.CharField(max_length=70, editable=False)
    order_placed = models.BooleanField(default=False)

    def __str__(self):        
        return self.product.title
     

    @property
    def price(self):
        if self.product_id is not None:
            return (self.product.price)


    @property
    def amount(self):
        if self.product_id is None:
            return (None)
        else:                
            if self.product.discount_price:
                return(self.product.discount_price * self.quantity)
            else:
                return(self.product.price * self.quantity)
                   

class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity','size']
       
      


class Order(models.Model):
    STATUS =(
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preparing', 'Preparing'),
        ('OnShipping', 'OnShipping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    total = models.FloatField(null=True, blank=True)
    order_placed = models.BooleanField(default=False)
    order_code = models.CharField(max_length=70, editable=False)
    payment_code = models.CharField(max_length=8, editable=False)
    first_name = models.CharField(max_length=15)
    last_name= models.CharField(max_length=15)
    phone= models.CharField(blank=True, max_length=20)
    address = models.CharField(max_length=150, blank=True)
    city = models.CharField(blank=True, max_length=20)
    state = models.CharField(blank=True, null=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    adminnote = models.CharField(blank=True, max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
       
    
    def __str__(self):
        return self.user.username



class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'address', 'phone', 'city', 'country']



    

order/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse

from django.contrib import messages
from home.models import Setting
from product.models import Category, Product
from .models import ShopCart, ShopCartForm, Order, OrderForm
from  user.models import UserProfile
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import requests
import json
import random
import string
import uuid
from django.views.decorators.http import require_POST




# Create your views here.
def index(request):
    return HttpResponse("Order App installed")


@require_POST
@login_required(login_url='/login')
def addtoshopcart(request):
    url = request.META.get('HTTP_REFERER')
    thequantity = int(request.POST['quantity'])
    thesize = request.POST.get('size', None)
    theprodid = request.POST['prodid']
    aprod = Product.objects.get(pk=theprodid)

     #check if the user has an existing cart
    cart = ShopCart.objects.filter(order_placed=False).filter(user__username = request.user.username)

    if cart: #an existing cart is noticed
        prodchecker = ShopCart.objects.filter(product_id = aprod.id, size=thesize, quantity=thequantity,user__username = request.user.username).first()
        
        if prodchecker: #product exists in the cart, increment it
            prodchecker.quantity += thequantity
            prodchecker.size = thesize
            prodchecker.save()
            messages.success(request, "Product added to Shopcart")
            return redirect(url)

        else: #product is not in the cart, add it
            anitem = ShopCart()
            anitem.product=aprod
            anitem.user=request.user
            anitem.order_code=cart[0].order_code
            anitem.quantity=thequantity
            anitem.size= thesize
            anitem.order_placed=False
            anitem.save()                
                 
        
    else: #create a new cart, generate  order code
        ordercode = str(uuid.uuid4())
        newcart = ShopCart()
        newcart.product=aprod
        newcart.user=request.user
        newcart.order_code=ordercode
        newcart.quantity=thequantity
        newcart.size= thesize
        newcart.order_placed=False
        newcart.save()

    messages.success(request, "Product added to Shopcart")

    return redirect(url)
    


@login_required(login_url='/login')
def shopcart(request):  
    category = Category.objects.all() 
    setting= Setting.objects.get(pk=1)
    shopcart = ShopCart.objects.filter(order_placed=False).filter(user__username=request.user.username)
    
    subtotal=0
    shippingfee = 0
    vat =0
    total = 0
    
    for item in shopcart:
        if item.product.discount_price:
            subtotal += item.product.discount_price * item.quantity
        else:
            subtotal += item.product.price * item.quantity

    # Shipping rules: 8% fees to all orders above 150. 0 fees to orders lower
    if subtotal > 150:
        shippingfee = 0.08 * subtotal
    else:
        shippingfee = 0

    vat = 0.075 * subtotal

    total = subtotal + shippingfee + vat
   
    
    context = { 
                'setting': setting,
                'category': category,
                'shopcart': shopcart,
                'subtotal': subtotal,
                'shipping': shippingfee,
                'vat': vat,
                'total':total
                 }

    return render(request, 'shopcart.html', context)


@require_POST
@login_required(login_url='/login')
def updatequantity(request):
    url = request.META.get('HTTP_REFERER')
    newquantity = request.POST['itemquantity']
    theitem = ShopCart.objects.get(id=request.POST['itemid'])
    theitem.quantity = newquantity
    theitem.save()

    messages.success(request, "Product Quantity successfully updated")
    return redirect(url)



@login_required(login_url='/login')
def deletefromcart(request,id):
    ShopCart.objects.filter(id=id).delete()
    messages.success(request, 'Item deleted from Shopcart.')
    return redirect('order:shopcart')


@login_required(login_url='/login')
def checkout(request):
    category = Category.objects.all()  
    setting= Setting.objects.get(pk=1)
    shopcart = ShopCart.objects.filter(user__username = request.user.username).filter(order_placed=False)
    profile= UserProfile.objects.get(user__username = request.user.username)

    subtotal=0
    shippingfee = 0
    vat = 0
    total = 0

    for item in shopcart:
        if item.product.discount_price:
            subtotal += item.product.discount_price * item.quantity
        else:
            subtotal += item.product.price * item.quantity 

    # Shipping rules: 8% fees to all orders above 150. 0 fees to orders lower
    if subtotal > 150:
        shippingfee = 0.08 * subtotal
    else:
        shippingfee = 0

    # vat is at 7.50% of the total purchase to  be made 
    vat = 0.075 * subtotal

    total = subtotal + shippingfee + vat    

    context = { 
                'setting': setting,                
                'shopcart': shopcart,
                'order_code': shopcart[0].order_code,
                'profile': profile,
                'category': category,               
                'subtotal': subtotal,
                'shipping': shippingfee,
                'vat': vat,
                'total':total
                 }
    return render(request, 'checkout.html', context)
    

@require_POST
@login_required(login_url='/login')
def placeorder(request):
    api_key = 'sk_test_c6ea6380a5503bbdaa7d7285bb0c4e86523c3613'
    url = 'https://api.paystack.co/transaction/initialize'
    callback_url = 'http://localhost:8000/order/ordercompleted/'
    ordercode =  request.POST['order_number']
    autogen_ref = ''.join(random.choices(string.digits + string.ascii_letters, k=8))
    current_user = User.objects.get(username = request.user.username)
    user = UserProfile.objects.get(user_id = current_user.id)
    total = float(request.POST['amount']) * 100    
    

    headers = {'Authorization': f'Bearer {api_key}'}
    data = {'reference': autogen_ref, 'amount':int(total), 'order_number':ordercode, 'email':user.email, 'callback_url':callback_url }

    
    # making a request to PAYSTACK 
    try:
        r = requests.post(url, headers=headers, json=data)
    except Exception:
        messages.error(request, 'Network busy. Please try again in few minutes. Thank You!')
    else:
        # create an order 
        transback = json.loads(r.text)
        
        rd_url = transback['data']['authorization_url']
        theuser= UserProfile.objects.filter(user=request.user).first()
        order = Order()
        order.first_name=theuser.user.first_name
        order.last_name=theuser.user.last_name
        order.phone=theuser.phone
        order.city=theuser.city
        order.order_code= ordercode
        order.payment_code = autogen_ref
        order.total=total
        order.order_placed = True
        order.save()
        return redirect(rd_url)
    return redirect('order:checkout')



@login_required(login_url='/login')
def ordercompleted(request):
    category = Category.objects.all()  
    setting= Setting.objects.get(pk=1)
    banner = Product.objects.get(banner=True)
    offer = Product.objects.get(offer=True)
    profile= UserProfile.objects.get(user__username = request.user.username)
    shopcart = ShopCart.objects.filter(order_placed=False).filter(user__username = request.user.username)
    
    #cleaning the shopcart
    for item in shopcart:
        item.order_placed = True
        item.save()
    
    
        #reducing quantity instock
        aproduct = Product.objects.get(id=item.product.id)
        aproduct.quantity_instock -= item.quantity
        aproduct.save() 


    context = {
                'setting': setting,
                'offer': offer,
                'category': category,
                'shopcart': shopcart,
                'profile': profile,
    }
    
    return render(request, 'ordercompleted.html', context)

order/templates/checkout.html
{% extends 'base.html' %}


{% load humanize %}

{% block title %} Checkout {% endblock title %}

{% block keywords %} {{setting.keywords}} {% endblock keywords %}

{% block description %} {{setting.description}} {% endblock description %}
    

        

<!-- Header and banner  -->
{% block header %} {% include "prod-header.html" %} {% endblock header %}
<!-- Header and banner done  -->

<!-- Content  -->
{% block content %}  

   <!-- Checkout Page  -->
    <div class="checkout-page" style="padding: 50px 0;">
        <h2 class="title">Checkout Page</h2>
        <div class="container">
            <div class="row">
                <div class="col-2">
                    <div class="form-container" style="height: 520px;">
                        <div class="form-buttons">
                            <h4 class="title"><strong>Order</strong> Details</h4>
                        </div>
                        <form action="{% url 'order:placeorder' %}" method="POST">
                        {% csrf_token %}
                            <input type="text" value="{{profile.first_name}}" placeholder="First Name">
                            <input type="text" value="{{profile.last_name}}" placeholder="Last Name">
                            <input type="text" value="{{profile.phone}}" placeholder="Phone Number">
                            <input type="text" value="{{profile.address}}" placeholder="Address">
                            <input type="text" value="{{profile.city}}" placeholder="City">
                            <input type="text" value="{{profile.state}}" placeholder="State">
                            <input type="text" value="{{profile.country}}" placeholder="Country">
                            <input type="hidden" name="amount" value="{{total}}">
                            <input type="hidden" name="order_number" value="{{order_code}}">
                            <button type="submit" class="buttons">Proceed To Order</button>
                        </form>	  
                    </div>
                </div>
                <div class="col-2">
                    <div class="small-container cart-page" style="height: 520px;width:520px;">
                        <div class="form-buttons">
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-success alert-{{message.tags}}" role="alert">
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        {{message}}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <h4 class="title" style="text-align: center;">Delivery Details</h4>
                        <table>
                            <tr>
                                <th>Product</th>
                                <th>Quantity</th>
                                <th>Size</th>
                                <th>Amount</th>
                            </tr>
                        {% if shopcart %}            
                            {% for item in shopcart %}
                                <tr>
                                    <td>
                                        <div class="cart-info">
                                            <div>
                                                <p>{{item.product.title}}</p>
                                            </div>  
                                        </div>    
                                    </td>
                                    <td>{{item.quantity}}</td>
                                    <td>{{item.size}}</td>
                                    <td>{{item.amount | floatformat:2 | intcomma}}</td>  
                                </tr>
                            {% endfor %}
                        {% endif %}
                        </table>
                        <div class="total-price">
                          <table>
                            <tr>
                                <td>Total</td>
                                <td>#{{total | floatformat:2 | intcomma}}</td>
                            </tr>
                          </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
   <!-- Checkout Page Done  -->

   {% endblock content %}                       
   <!-- Content done  -->

   <!-- footer   -->
   {% block footer %}  {% include "footer.html" %} {% endblock footer %}
   <!-- footer done  -->

   


    

order/templates/ordercompleted.html
{% extends 'base.html' %}


{% load humanize %}


{% block title %} Order Completed  {% endblock title %}

{% block keywords %} {{product.keywords}} {% endblock keywords %}

{% block description %} {{product.description}} {% endblock description %}
     
<!-- Header   -->
{% block header %} {% include "acheader.html" %} {% endblock header %}
<!-- Header done  -->


{% block content %}
<!-- order completed details  -->
<div class="account-page">
    <div class="container">
        <h2 class="text-center">Order Completed</h2>
        <div class="row">
            <div class="col-2">
                <div class="oform-container">
                    <h4>Dear <span style="color: #ff523b;">{{profile.user.username}} {{profile.user.last_name}}</span></h4>
                    <h5>Your Order is Completed</h5>
                    <p>Thank You for your patronage</p>
                </div>
            </div>
            <div class="col-2">
                <div class="row">
                    <div class="col-2">
                        <img src="{{offer.image.url}}" class="offer-img">
                    </div>
                </div>
            </div>
            <div class="col-2">
                <p>Exclusively Aavailable at Prodigious Store</p>
                <h1>Lingerie </h1>
                <small>
                    Our range of women's lingerie is a must have in any underwear drawer. 
                    So, get ready to impress while you undress with the best range of lingerie.
                </small>
                <a href="{% url 'category' %}" class="buttons">Buy Now &#8594;</a>
            </div>
        </div>
    </div>
</div>
                                                                                                                                                                                                                                                                            
<!-- order completed details end here  -->
{% endblock content %}

<!-- footer   -->
{% block footer %}  {% include "footer.html" %} {% endblock footer %}
<!-- footer done  -->

order/templates/shopcart.html
{% extends 'base.html' %}


{% load humanize %}


{% block title %} Shopcart {% endblock title %}

{% block keywords %} {{product.keywords}} {% endblock keywords %}

{% block description %} {{product.description}} {% endblock description %}
     
<!-- Header   -->
{% block header %} {% include "prod-header.html" %} {% endblock header %}
<!-- Header done  -->


{% block content %}
    <!-- Cart items details  -->
    <div class="small-container cart-page">
        <table>
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Size</th>
                <th>Amount</th>
            </tr>
        
        {% if shopcart %}            
            {% for item in shopcart %}
                <tr>
                    <td>
                        <div class="cart-info">
                            <img src="{{item.product.image.url}}">
                            <div>
                                <p>{{item.product.title}}</p>
                                <small>
                                    {% if item.discount_price %}
                                        {{item.discount_price | floatformat:2 | intcomma}}
                                    {% else %}
                                        {{item.price | floatformat:2 | intcomma}}
                                    {% endif %}                                                     
                                </small>
                                <br>
                                <a href="{% url 'order:deletefromcart' item.id %}">Remove</a>
                                <form  action="{% url 'order:updatequantity' %}" method="post">
                                {% csrf_token %}
                                    <input style="width: 70px; height:20px" type="number"  id="item" name="itemquantity" value="{{item.quantity}}" min="{{item.product.minquantity}}" max="{{item.product.quantity_instock}}">                                    
                                    <button type="submit" style="color:#ff523b;font-size: 12px;border:none;border:none; outline:none">Update Quantity</button>
                                    <input type="hidden" name="itemid" value="{{ item.id }}">
                                </form>
                            </div>  
                        </div>    
                    </td>
                    <td>{{item.quantity}}</td>
                    <td>{{item.size}}</td>
                    <td>{{item.amount | floatformat:2 | intcomma}}</td>  
                </tr>
            {% endfor %}
        {% endif %}
        </table>
        <div class="total-price">
          <table>
            <tr>
                <td>Subtotal</td>
                <td>{{subtotal | floatformat:2 | intcomma}}</td>
            </tr>
            <tr>
                <td>Shipping</td>
                <td>{{shipping | floatformat:2 | intcomma}}</td>
            </tr>
            <tr>
                <td>Vat(7.50%)</td>
                <td>{{vat | floatformat:2 | intcomma}}</td>
            </tr>
            <tr>
                <td>Total</td>
                <td>#{{total | floatformat:2 | intcomma}}</td>
            </tr>
          </table>
        </div>
        <div class="total-price">
            <table>
              <tr>
                  <td><a href="{% url 'category' %}" class="buttons">Continue</a></td>
                  <td><a href="{% url 'order:checkout' %}" class="buttons">Checkout</a></td>
              </tr>
            </table>
        </div>
    </div>
    <!-- cart items details end here  -->
{% endblock content %}

<!-- footer   -->
{% block footer %}  {% include "footer.html" %} {% endblock footer %}
<!-- footer done  -->